version: '3.8'

services:
# TODO RESTART ON FALIURE
  webserver:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/out/:/var/www/html
    ports:
    - "80:80"
    links:
      - backend

  backend:
    image: root.backend.api:8080/api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: &pg_user admin
      PGUSER: *pg_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: &pg_database redscooter
      PGDATABASE: *pg_database
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    command: postgres -c listen_addresses='*' # todo removes this and use network config
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 0s
