version: "3.8"
services:
# TODO RESTART ON FALIURE
  webserver:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/out/html:/var/www/html
    ports:
    - "80:80"

  backend:
    image: root.backend.api:8080/api:latest
    # environment:
    #   SITE: Plone
    #   RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
    ports:
    - "8080:8080"
    depends_on:
      - db
    links:
      - db
    extra_hosts:
        - "host.docker.internal:host-gateway"

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: redscooter
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    command: postgres -c listen_addresses='*' # todo removes this and use network config