server:
    port: 8080
    forward-headers-strategy: framework
    domain: https://redscooter.al/
    error:
        include-stacktrace: never
        include-message: never


spring-doc:
    swagger-ui:
        disable-swagger-default-url: true
        operations-sorter: method
        path: /api-docs/swagger-ui.html
        config-url: /api-docs/v3/swagger-config

        urls-primary-name: All
        urls[0]:
            name: All
            url: /api-docs/v3
        urls[1]:
            name: Public
            url: /api-docs/v3/public
        urls[2]:
            name: Admin
            url: /api-docs/v3/admin
        urls[3]:
            name: User
            url: /api-docs/v3/user

    api-docs:
        path: /api-docs/v3
        groups:
            enabled=true:


cors:
    allowed-origins:
        - 'http://localhost:3000'
        - 'http://75.119.149.135:3000'
        - 'https://www.redscooter.al/'
        - 'https://redscooter.al/'
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    allowed-headers: "*"
#  exposed-headers: "X-Get-Header"

spring:
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                enable_lazy_load_no_trans: true
                jdbc:
                    batch_size: 50
                    time_zone: UTC
#                metadata_builder_contributor: com.redscooter.config.SqlFunctionsMetadataBuilderContributor
        hibernate:
            ddl-auto: update # none, create, create-drop, validate, and update
            enhancer:
                enableLazyInitialization: true

        show-sql: true

    datasource:
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD:postgres}
        url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/redscooter?reWriteBatchedInserts=true


jwt:
    access-token:
        expires-in: 3600000 # millis // 1H
    refresh-token:
        expires-in: 7776000000 # millis
    secret: ${JWT_SECRET:}
    issuer: REDSCOOTER.AL

email:
    username: "redscooter.al@gmail.com"
    password: ${SMTP_PASSWORD:}
    host: "smtp.gmail.com"
    port: 587
    protocol: "smtp"
    debug: true
    auth: true
    starttls: true

#FileStore:


